module.exports = [
    // { group: 'Container', show: true, name: 'u-router-view', alias: '子页面容器' },
    // { group: 'Container', show: true, name: 'u-iframe', alias: 'Iframe' },
    // { group: 'Layout', show: true, name: 'u-linear-layout', alias: '线性布局', vscode: false },
    // { group: 'Layout', show: true, name: 'u-grid-layout', alias: '栅格布局', vscode: false },
    // { group: 'Layout', show: true, name: 'u-navbar', alias: '导航栏' },
    // { group: 'Layout', show: true, name: 'u-sidebar', alias: '侧边栏' },
    // { group: 'Layout', show: true, name: 'u-footbar', alias: '底部栏', newest: true },
    // { group: 'Layout', show: true, name: 'u-crumb', alias: '面包屑' },
    // { group: 'Layout', show: true, name: 'u-panel', alias: '面板' },
    // { group: 'Layout', show: true, name: 'u-collapse', alias: '折叠面板' },
    { group: 'Container', show: true, name: 'router-view', alias: '子页面' },
    { group: 'Container', show: true, name: 'popup', alias: '弹出层' },
    { group: 'Layout', show: true, name: 'divider', alias: '分割线' },
    { group: 'Layout', show: true, name: 'cell-group', alias: '单元格' },
    { group: 'Layout', show: true, name: 'row', alias: '栅格' },
    { group: 'Display', show: true, name: 'button', alias: '按钮' },
    { group: 'Display', show: true, name: 'image', alias: '图片' },
    { group: 'Display', show: true, name: 'swipe', alias: '轮播' },
    { group: 'Display', show: true, name: 'tabs', alias: '选项卡' },
    { group: 'Display', show: true, name: 'text', alias: '文本' },
    { group: 'Form', show: true, name: 'form', alias: '表单' },
    // { group: 'Form', show: true, name: 'u-input', alias: '单行输入' },
    // { group: 'Form', show: true, name: 'u-number-input', alias: '数字输入' },
    // { group: 'Form', show: true, name: 'u-textarea', alias: '多行输入' },
    { group: 'Form', show: true, name: 'radio-group', alias: '单选组' },
    { group: 'Form', show: true, name: 'switch', alias: '开关' },
    { group: 'Form', show: true, name: 'checkbox-group', alias: '多选组' },
    { group: 'Form', show: true, name: 'stepper', alias: '步进器' },
    // { group: 'Form', show: true, name: 'u-capsules', alias: '胶囊' },
    // { group: 'Form', show: true, name: 'u-select', alias: '选择框' },
    // { group: 'Form', show: true, name: 'u-rate', alias: '评分' },
    // { group: 'Form', show: true, name: 'u-combo-slider', alias: '滑块' },
    { group: 'Form', show: true, name: 'uploader', alias: '文件上传' },
    { group: 'Selector', show: true, name: 'picker', alias: 'picker选择器' },
    { group: 'Selector', show: true, name: 'area', alias: '地区选择器' },
    { group: 'Selector', show: true, name: 'cascader', alias: '级联选择器' },
    { group: 'Selector', show: true, name: 'datetime-picker', alias: '时间选择器' },
    { group: 'Selector', show: true, name: 'calendar', alias: '日期选择器' },
    { group: 'Feedback', show: true, name: 'dialog', alias: '弹出框' },


    // { group: 'Display', show: true, name: 'u-text', alias: '文本' },
    // { group: 'Display', show: true, name: 'u-link', alias: '链接' },
    // { group: 'Display', show: true, name: 'u-button', alias: '按钮' },
    // { group: 'Display', show: true, name: 'i-icon', alias: '图标' },
    // { group: 'Display', show: true, name: 'u-label', alias: '标签' },
    // { group: 'Display', show: true, name: 'u-badge', alias: '徽章' },
    // { group: 'Display', show: true, name: 'u-carousel', alias: '走马灯' },
    // { group: 'Display', show: true, name: 'u-info-list', alias: '详情列表' },
    // { group: 'Display', show: true, name: 'u-image', alias: '图片展示' },

    // { group: 'Table', show: true, name: 'u-table-view', alias: '数据表格' },
    // { group: 'Table', show: true, name: 'u-form-table-view', alias: '表单表格', newest: true },
    // // { group: 'Table', show: true, name: 'u-list-view', alias: '数据列表' },
    // // { group: 'Table', show: true, name: 'u-actions', alias: '操作项' },

    // { group: 'Selector', show: true, name: 'u-tabs', alias: '选项卡' },
    // { group: 'Selector', show: true, name: 'u-selectable-steps', alias: '步骤条', vscode: false },
    // { group: 'Selector', show: true, name: 'u-pagination', alias: '翻页器' },
    // { group: 'Selector', show: true, name: 'u-cascade-select', alias: '级联选择' },
    // { group: 'Selector', show: true, name: 'u-region-select', alias: '地区选择' },
    // { group: 'Selector', show: true, name: 'u-tree-view', alias: '树型列表' },
    // { group: 'Selector', show: true, name: 'u-transfer', alias: '穿梭框' },
    // { group: 'Selector', show: true, name: 'u-date-picker', alias: '日期选择' },
    // { group: 'Selector', show: true, name: 'u-time-picker', alias: '时间选择' },
    // { group: 'Selector', show: true, name: 'u-date-time-picker', alias: '日期时间' },

    // { group: 'Chart', show: true, name: 'u-linear-progress', alias: '线型进度条' },
    // { group: 'Chart', show: true, name: 'u-circular-progress', alias: '圆型进度条' },

    // { group: 'Feedback', show: true, name: 'u-popup', alias: '弹出框' },
    // { group: 'Feedback', show: true, name: 'u-modal', alias: '弹窗' },

    // { group: 'Effects', show: true, name: 'e-watermark', alias: '水印' },
    // { group: 'Effects', show: true, name: 'u-copy', alias: '复制', newest: true, vscode: false },

    // { group: 'Process', show: true, name: 'u-taskbox', alias: '任务箱' },
];
