export type ConfigProviderThemeVars =
  import('../action-bar').ActionBarThemeVars &
    import('../action-bar-button').ActionBarButtonThemeVars &
    import('../action-bar-icon').ActionBarIconThemeVars &
    import('../action-sheet').ActionSheetThemeVars &
    import('../address-edit').AddressEditThemeVars &
    import('../address-list').AddressListThemeVars &
    import('../badge').BadgeThemeVars &
    import('../button').ButtonThemeVars &
    import('../calendar').CalendarThemeVars &
    import('../card').CardThemeVars &
    import('../cascader').CascaderThemeVars &
    import('../cell').CellThemeVars &
    import('../cell-group').CellGroupThemeVars &
    import('../checkbox').CheckboxThemeVars &
    import('../circle').CircleThemeVars &
    import('../collapse-item').CollapseItemThemeVars &
    import('../contact-card').ContactCardThemeVars &
    import('../contact-edit').ContactEditThemeVars &
    import('../contact-list').ContactListThemeVars &
    import('../count-down').CountDownThemeVars &
    import('../coupon').CouponThemeVars &
    import('../coupon-cell').CouponCellThemeVars &
    import('../coupon-list').CouponListThemeVars &
    import('../dialog').DialogThemeVars &
    import('../divider').DividerThemeVars &
    import('../dropdown-item').DropdownItemThemeVars &
    import('../dropdown-menu').DropdownMenuThemeVars &
    import('../empty').EmptyThemeVars &
    import('../field').FieldThemeVars &
    import('../grid-item').GridItemThemeVars &
    import('../image').ImageThemeVars &
    import('../image-preview').ImagePreviewThemeVars &
    import('../index-anchor').IndexAnchorThemeVars &
    import('../index-bar').IndexBarThemeVars &
    import('../list').ListThemeVars &
    import('../loading').LoadingThemeVars &
    import('../nav-bar').NavBarThemeVars &
    import('../notice-bar').NoticeBarThemeVars &
    import('../notify').NotifyThemeVars &
    import('../number-keyboard').NumberKeyboardThemeVars &
    import('../overlay').OverlayThemeVars &
    import('../pagination').PaginationThemeVars &
    import('../password-input').PasswordInputThemeVars &
    import('../picker').PickerThemeVars &
    import('../picker-group').PickerGroupThemeVars &
    import('../popover').PopoverThemeVars &
    import('../popup').PopupThemeVars &
    import('../progress').ProgressThemeVars &
    import('../pull-refresh').PullRefreshThemeVars &
    import('../radio').RadioThemeVars &
    import('../rate').RateThemeVars &
    import('../search').SearchThemeVars &
    import('../share-sheet').ShareSheetThemeVars &
    import('../sidebar').SidebarThemeVars &
    import('../sidebar-item').SidebarItemThemeVars &
    import('../skeleton').SkeletonThemeVars &
    import('../slider').SliderThemeVars &
    import('../step').StepThemeVars &
    import('../stepper').StepperThemeVars &
    import('../steps').StepsThemeVars &
    import('../sticky').StickyThemeVars &
    import('../submit-bar').SubmitBarThemeVars &
    import('../swipe').SwipeThemeVars &
    import('../switch').SwitchThemeVars &
    import('../tabbar').TabbarThemeVars &
    import('../tabbar-item').TabbarItemThemeVars &
    import('../tabs').TabsThemeVars &
    import('../tag').TagThemeVars &
    import('../toast').ToastThemeVars &
    import('../tree-select').TreeSelectThemeVars &
    import('../uploader').UploaderThemeVars;
