const pkg = require('./package.json');

module.exports = {
    version: '>=0.1.1',
    type: 'library',
    name: '@lcap/mobile-ui',
    CamelName: 'LcapMobileUI',
    docs: {
        title: '@lcap/mobile-ui组件库',
        logo: '组件库',
        github: 'https://github.com/vusion/vant',
        package: pkg,
        navbar: [
            // { text: '设计语言', to: '/design' },
            { text: '基础组件', to: '/components' },
            { text: '指令和工具', to: '/misc' },
            { text: '布局', to: '/layouts' },
        ],
        components: [
            { group: 'Layout', show: true, name: 'divider', alias: '分割线' },
            { group: 'Layout', show: true, name: 'cell-group', alias: '单元格' },
            { group: 'Layout', show: true, name: 'row', alias: '栅格' },
            { group: 'Display', show: true, name: 'button', alias: '按钮' },
            { group: 'Display', show: true, name: 'image', alias: '图片' },
            { group: 'Display', show: true, name: 'swipe', alias: '轮播' },
            { group: 'Container', show: true, name: 'popup', alias: '弹出层' },
            { group: 'Container', show: true, name: 'router-view', alias: '子页面' },
            { group: 'Display', show: true, name: 'tabs', alias: '选项卡' },
            { group: 'Display', show: true, name: 'text', alias: '文本' },
            { group: 'Form', show: true, name: 'form', alias: '表单' },
            // { group: 'Form', show: true, name: 'u-input', alias: '单行输入' },
            // { group: 'Form', show: true, name: 'u-number-input', alias: '数字输入' },
            // { group: 'Form', show: true, name: 'u-textarea', alias: '多行输入' },
            { group: 'Form', show: true, name: 'radio-group', alias: '单选组' },
            { group: 'Form', show: true, name: 'switch', alias: '开关' },
            { group: 'Form', show: true, name: 'checkbox-group', alias: '多选组' },
            { group: 'Form', show: true, name: 'stepper', alias: '步进器' },
            // { group: 'Form', show: true, name: 'u-capsules', alias: '胶囊' },
            // { group: 'Form', show: true, name: 'u-select', alias: '选择框' },
            // { group: 'Form', show: true, name: 'u-rate', alias: '评分' },
            // { group: 'Form', show: true, name: 'u-combo-slider', alias: '滑块' },
            { group: 'Form', show: true, name: 'uploader', alias: '文件上传' },
            { group: 'Selector', show: true, name: 'picker', alias: 'picker选择器' },
            { group: 'Selector', show: true, name: 'area', alias: '地区选择器' },
            { group: 'Selector', show: true, name: 'cascader', alias: '级联选择器' },
            { group: 'Selector', show: true, name: 'datetime-picker', alias: '时间选择器' },
            { group: 'Selector', show: true, name: 'calendar', alias: '日期选择器' },
            { group: 'Feedback', show: true, name: 'dialog', alias: '弹出框' },
        ],
        blocks: [],
        directives: [
            // { group: 'Directive', name: 'v-repeat-click' },
            // // { group: 'Directive', name: 'v-click-outside' },
            // { group: 'Directive', name: 'v-ellipsis-title' },
            // { group: 'Directive', name: 'v-focus' },
        ],
        filters: [],
        utils: [
            // { group: 'Utils', name: 'DataSource', alias: '数据源' },
            // { group: 'Utils', name: 'Formatters', alias: '格式器' },
            { group: 'Utils', name: 'dom', alias: 'DOM 相关' },
            { group: 'Utils', name: 'edit', alias: '编辑相关' },
        ],
        layouts: [
            { group: 'Layout', name: 'l-dashboard', alias: '仪表盘布局' },
            { group: 'Layout', name: 'l-document', alias: '文档布局' },
            { group: 'Layout', name: 'l-page', alias: '通用页面布局' },
            { group: 'Layout', name: 'l-side-main', alias: '左侧栏固定布局' },
            { group: 'Layout', name: 'l-left-middle-right', alias: '左中右布局' },
            { group: 'Layout', name: 'l-wrapper', alias: '透传页' },
            { group: 'Layout', name: 'l-root', alias: '界面根节点' },
        ],
    },
};
