module.exports = {
  extends: [
    'airbnb-base',
    'plugin:vue/recommended',
    'prettier',
    'prettier/vue',
  ],

  parserOptions: {
    parser: '@typescript-eslint/parser',
    ecmaVersion: 2018,
    sourceType: 'module',
    extraFileExtensions: ['.vue'],
  },

  plugins: ['@typescript-eslint'],

  env: {
    es6: true,
    node: true,
    jest: true,
    browser: true,
  },

  rules: {
    camelcase: 0,
    'no-new': 0,
    'no-shadow': 0,
    'no-bitwise': 0,
    'func-names': 0,
    'no-console': 0,
    'no-plusplus': 0,
    'default-case': 0,
    'prefer-template': 0,
    'consistent-return': 0,
    'no-param-reassign': 0,
    'no-nested-ternary': 0,
    'no-underscore-dangle': 0,
    'no-unused-expressions': 0,
    'no-restricted-globals': 0,
    'class-methods-use-this': 0,
    'prefer-destructuring': ['error', { object: true, array: false }],
    'import/order': 0,
    'import/extensions': 0,
    'import/no-unresolved': 0,
    'import/prefer-default-export': 0,
    'import/no-extraneous-dependencies': 0,
    'vue/no-v-html': 0,
    'vue/attributes-order': 0,
    'vue/require-v-for-key': 0,
    'vue/require-default-prop': 0,
    'vue/no-unused-components': 0,
    'vue/name-property-casing': ['error', 'kebab-case'],
    'vue/component-name-in-template-casing': ['error', 'kebab-case'],
    '@typescript-eslint/no-unused-vars': ['error'],
  },
};
