export type SubmitBarThemeVars = {
  submitBarHeight?: string;
  submitBarZIndex?: string;
  submitBarBackground?: string;
  submitBarButtonWidth?: string;
  submitBarPriceColor?: string;
  submitBarPriceFontSize?: string;
  submitBarPriceIntegerFontSize?: string;
  submitBarPriceFont?: string;
  submitBarCurrencyFontSize?: string;
  submitBarTextColor?: string;
  submitBarTextFontSize?: string;
  submitBarTipPadding?: string;
  submitBarTipFontSize?: string;
  submitBarTipLineHeight?: string;
  submitBarTipColor?: string;
  submitBarTipBackground?: string;
  submitBarTipIconSize?: string;
  submitBarButtonHeight?: string;
  submitBarPadding?: string;
};
