export type NumberKeyboardThemeVars = {
  numberKeyboardBackground: string;
  numberKeyboardKeyHeight: string;
  numberKeyboardKeyFontSize: string;
  numberKeyboardKeyActiveColor: string;
  numberKeyboardKeyBackground: string;
  numberKeyboardDeleteFontSize: string;
  numberKeyboardTitleColor: string;
  numberKeyboardTitleHeight: string;
  numberKeyboardTitleFontSize: string;
  numberKeyboardClosePadding: string;
  numberKeyboardCloseColor: string;
  numberKeyboardCloseFontSize: string;
  numberKeyboardButtonTextColor: string;
  numberKeyboardButtonBackground: string;
  numberKeyboardZIndex: string;
  numberKeyboardBackground: string;
  numberKeyboardKeyBackground: string;
  numberKeyboardKeyActiveColor: string;
};
