name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  reply-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == '👏 PR welcome' || github.event.label.name == 'help wanted'
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) for it. Please send your Pull Request to `main` branch, provide changelog/TypeScript/documentation/test cases if needed and make sure CI passed, we will review it soon. We appreciate your effort in advance and looking forward to your contribution!

            你好 @${{ github.event.issue.user.login }}，我们完全同意你的提议/反馈，欢迎直接在此仓库 [创建一个 Pull Request](https://help.github.com/en/articles/creating-a-pull-request) 来解决这个问题。请将 Pull Request 发到 `main` 分支，提供改动所需相应的 changelog、TypeScript 定义、测试用例、文档等，并确保 CI 通过，我们会尽快进行 Review，提前感谢和期待你的贡献。
        run: gh issue comment "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --body "$COMMENT_BODY"

      - name: need reproduce
        if: github.event.label.name == 'need reproduce'
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: |
            Hello @${{ github.event.issue.user.login }}. Please provide an online reproduction demo by [codesandbox](https://codesandbox.io/p/devbox/vant-4-issue-template-8fuq5o) or a minimal GitHub repository. Issues marked with `need reproduce` will be closed if there is no activity within 3 days. For background, please refer to [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

            你好 @${{ github.event.issue.user.login }}, 我们需要你提供一个在线的重现示例，以便于我们帮你排查问题。你可以通过点击 [codesandbox](https://codesandbox.io/p/devbox/vant-4-issue-template-8fuq5o) 创建，或者提供一个最小化的 GitHub 仓库。如果 3 天内未跟进，此 issue 将会被自动关闭。背景请参考 [为什么需要最小重现](https://antfu.me/posts/why-reproductions-are-required-zh)。
        run: gh issue comment "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --body "$COMMENT_BODY"

      - name: question
        if: github.event.label.name == 'question'
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: |
            Hello @${{ github.event.issue.user.login }}, we use GitHub issues to trace bugs or discuss plans of Vant. So, please don't ask usage questions here. You can open a new discussion in [Vant Discussions](https://github.com/vant-ui/vant/discussions), select `Q&A` to ask questions.

            你好 @${{ github.event.issue.user.login }}，Vant Issue 板块是用于 bug 反馈与需求讨论的地方。请勿在这里询问如何使用等相关问题，你可以在 [Vant Discussions](https://github.com/vant-ui/vant/discussions) 新开一个 discussion，选择 `Q&A` 类别进行提问。
        run: gh issue close "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --comment "$COMMENT_BODY"

      - name: 2.x
        if: github.event.label.name == '2.x'
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: |
            Hi @${{ github.event.issue.user.login }}. Current version (2.x) has reached End of Life. We recommend using the latest 4.x version (LTS). This issue will be auto closed.

            你好 @${{ github.event.issue.user.login }}，当前版本（2.x）已经终止支持且不再维护。我们建议使用最新的 4.x 版本。当前 issue 会被自动关闭。
        run: gh issue close "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --comment "$COMMENT_BODY"

      - name: 3.x
        if: github.event.label.name == '3.x'
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: |
            Hi @${{ github.event.issue.user.login }}. Current version (3.x) has reached End of Life. We recommend using the latest 4.x version (LTS). This issue will be auto closed.

            你好 @${{ github.event.issue.user.login }}，当前版本（3.x）已经终止支持且不再维护。我们建议使用最新的 4.x 版本。当前 issue 会被自动关闭。
        run: gh issue close "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --comment "$COMMENT_BODY"

      - name: invalid
        if: github.event.label.name == 'invalid'
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENT_BODY: |
            Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not conform to our issue requirements.

            你好 @${{ github.event.issue.user.login }}，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。
        run: gh issue close "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --comment "$COMMENT_BODY"
