name: Create Release Tag

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: read

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      # Create the GitHub release and generate its notes.
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Create Release for Tag
        id: release_tag
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          generateReleaseNotes: "true"
